---
layout: cv
title: Jose Estradas's CV
---
Finance and Economy focusing in Financial Analyst on Private Equity


### Research interests

Private Equity, Investment Banking, Asset Management and Portfolio Management

### **Education**

**Bachelor of Science in Financial Economics**  
*Brigham Young University–Idaho*  
**Rexburg, ID** | *September 2021 – December 2025*  
- Minor in Data Science  
- GPA: 3.4 / 4.0 | Major GPA: 3.5 / 4.0



## KEY SKILLS AND CERTIFICATES
- Business Intelligence & Visualization: Power BI, Microsoft Excel, Tableau
- Participated in the CFA Institute Research Challenge, conducted the valuation, and equity research on a
- publicly traded company
- Financial Modeling and Forecasting Financial Statements Certificate
- Programming & Data Management: R, SQL (MySQL, Statistical & Data Analysis)
- Participant, Bloomberg Global Trading Challenge, collaborated as a team leader of five to supervise a virtual
- investment portfolio of $1M in a global competitive environment
- Bloomberg Market Concepts Certificate



### **Experience**

**Teaching Assistant**  
*Brigham Young University–Idaho, Department of Economics*  
**Rexburg, ID** | *August 2022 – Present*  
- Reviewed weekly performance of 90+ students across multiple sections, implementing targeted teaching strategies.  
- Coordinated a team of TAs in designing and executing feedback systems, significantly boosting teaching outcomes.

**Finance Intern**  
*The Church of Jesus Christ of Latter-day Saints*  
**Salt Lake City, UT** | *April 2024 – September 2024*  
- Analyzed 25,000+ properties across the U.S. using Power BI to support data-driven decision-making.  
- Corrected over 5,000 property record errors using advanced Excel data validation techniques to improve accuracy and reliability.

**CPA Assistant**  
*Contadores Fiscales Especializados, E.G*  
**Chiapas, Mexico** | *January 2020 – February 2021*  
- Maintained financial records by processing 500+ journal entries with Conta Fiscal software.  
- Organized and updated balance sheets, income statements, and accounting records to ensure audit readiness.
"""



### **Projects**

**Financial Analysis Project**  
- Analyzed Weighted Average Cost of Capital (WACC) trends, identifying a 5.9% hurdle rate optimal for capital budgeting.  
- Informed leadership on investment risk and return expectations to support strategic decision-making.  
- Streamlined financial comparisons across top firms using Excel and Bloomberg to clarify market positioning and enhance financial strategy.

**Investment Portfolio Analysis (Power BI)**  
- Developed an interactive Power BI dashboard analyzing 1,000+ ETFs, indexes, and mutual funds to identify optimal portfolio combinations.  
- Extracted and integrated financial data from Morningstar and Yahoo Finance, including yield and risk metrics.  
- Supported fund performance analysis and portfolio optimization through data-driven insights.
"""


<!-- ### Footer

Last updated: May 2013 -->